# Glob

env:
  - CABALVER=1.22 GHCVER=7.10.3 GLOB_DB="-fwith-postgresql" GLOB_TLS="-f-with-tls" GLOB_LA="-flaunch-docker" GLOB_DF="./dockerfiles/Travis-CI/Nginx/Dockerfile" GLOB_DT="postgres" NGINX="true"
  - CABALVER=1.22 GHCVER=7.10.3 GLOB_DB="-fwith-postgresql" GLOB_TLS="-f-with-tls" GLOB_LA="-flaunch-docker" GLOB_DF="./dockerfiles/Travis-CI/PostgreSQL/Dockerfile" GLOB_DT="postgres" NGINX="false"
  - CABALVER=1.22 GHCVER=7.10.3 GLOB_DB="-fwith-postgresql" GLOB_TLS="-fwith-tls" GLOB_LA="-flaunch-docker" GLOB_DF="./dockerfiles/Travis-CI/PostgreSQL/Dockerfile" GLOB_DT="postgres-tls" NGINX="false"
  - CABALVER=1.22 GHCVER=7.10.3 GLOB_DB="-fwith-mongodb" GLOB_TLS="-f-with-tls" GLOB_LA="-flaunch-docker" GLOB_DF="./dockerfiles/Travis-CI/MongoDB/Dockerfile" GLOB_DT="mongodb" NGINX="false"
  - CABALVER=1.22 GHCVER=7.10.3 GLOB_DB="-fwith-mongodb" GLOB_TLS="-fwith-tls" GLOB_LA="-flaunch-docker" GLOB_DF="./dockerfiles/Travis-CI/MongoDB/Dockerfile" GLOB_DT="mongodb-tls" NGINX="false"
  - CABALVER=1.22 GHCVER=7.10.3 GLOB_DB="-fwith-mysql" GLOB_TLS="-f-with-tls" GLOB_LA="-flaunch-docker" GLOB_DF="./dockerfiles/Travis-CI/MySQL/Dockerfile" GLOB_DT="mysql" NGINX="false"
  - CABALVER=1.22 GHCVER=7.10.3 GLOB_DB="-fwith-mysql" GLOB_TLS="-fwith-tls" GLOB_LA="-flaunch-docker" GLOB_DF="./dockerfiles/Travis-CI/MySQL/Dockerfile" GLOB_DT="mysql-tls" NGINX="false"
services:
  - docker

before_install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - "sudo add-apt-repository -y ppa:hvr/ghc"
  - "sudo apt-get update"
  - "sudo apt-get -y install ghc-$GHCVER cabal-install-$CABALVER llvm"
  - "export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH"
  - "cabal update"
  - "cabal install -j9 directory process persistent-template yesod persistent-postgresql persistent-mongoDB warp-tls cmdargs SHA"
script:
  - mkdir dist
  - cd glob-auth
  - cabal install --ghc-options=-fllvm
  - cd ../glob-core
  - cabal install $GLOB_DB $GLOB_TLS
  - cd ../glob-main --ghc-options=-fllvm
  - cabal install $GLOB_TLS
  - cd ../glob-launcher --ghc-options=-fllvm
  - cabal configure $GLOB_LA $GLOB_TLS $GLOB_DB --ghc-options=-fllvm
  - cabal build --ghc-options=-fllvm
  - cp -r dist  ../dist
  - cd ..
after_script: |
  if [ $TRAVIS_TEST_RESULT -eq 0 ]; then
    if [ $NGINX -eq "false" ];then
      echo "There should build a docker image."
      if [ -n "$TRAVIS_TAG" ]; then
        export DOCKER_IMAGE_TAG=$TRAVIS_BUILD_NUMBER-$TRAVIS_TAG-$GLOB_DT
      else
        export DOCKER_IMAGE_TAG=$TRAVIS_BUILD_NUMBER-$TRAVIS_COMMIT-$GLOB_DT
      fi
      cp $GLOB_DF dist
      cd dist && docker build -f Dockerfile -t qinka/glob:$DOCKER_IMAGE_TAG . && cd ..
      docker push  qinka/glob
    else
      echo "Build with nginx"
      if [ -n "$TRAVIS_TAG" ]; then
        export DOCKER_IMAGE_TAG=$TRAVIS_BUILD_NUMBER-$TRAVIS_TAG-$GLOB_DT
      else
        export DOCKER_IMAGE_TAG=$TRAVIS_BUILD_NUMBER-$TRAVIS_COMMIT-$GLOB_DT
      fi
      cd dist && mkdir shell && cd ..
      cp nginx/run.sh    dist/shell
      cp nginx/create.sh dist/shell
      chmod a+x dist/shell/run.sh
      chmod a+x dist/shell/create.sh
      cp $GLOB_DF dist
      cd dist && docker build -f Dockerfile -t qinka/glob:$DOCKER_IMAGE_TAG . && cd ..
      docker push  qinka/glob
    fi
  fi
