# The config of Travis

#to use ubuntu 14.04
sudo: required
dist: trusty

# setting cache
cache:
  - $HOME/.stack
# the matrix of settings
matrix:
  include:
    - env: GHC_VER=8.0.2 THREADED=t RUN_TEST=t DEBUG=debug RUN_BUILD=true STACKSOLVER=stack-lts-9.0.yaml LLVM=3.7
      addons:
        apt:
          sources:
            - hvr-ghc
          packages:
            - wget
            - curl
            - ghc-8.0.2
    - env: GHC_VER=8.0.2 THREADED=t RUN_TEST=t DEBUG=debug RUN_BUILD=true STACKSOLVER=stack-lts-9.0.yaml
      addons:
        apt:
          sources:
            - hvr-ghc
          packages:
            - wget
            - curl
            - ghc-8.0.2
            - ghc-8.0.2
    - env: GHC_VER=8.2.1 THREADED=t RUN_TEST=t DEBUG=debug RUN_BUILD=true
      addons:
        apt:
          sources:
            - hvr-ghc
          packages:
            - wget
            - curl
            - ghc-8.2.1
    - env: GHC_VER=8.2.1 THREADED=t RUN_TEST=t DEBUG=debug IS_DOCKER=docker LLVM=3.9 RUN_BUILD=true
      addons:
        apt:
          sources:
            - hvr-ghc
          packages:
            - ghc-8.2.1
            - curl
            - wget


# using docker
services:
  - docker

# pre-install
before_install:
  - source $TRAVIS_BUILD_DIR/.integration/TravisScript/before.sh


# build
script:
  - source $TRAVIS_BUILD_DIR/.integration/TravisScript/test.sh
  - source $TRAVIS_BUILD_DIR/.integration/TravisScript/build.sh

# update docker image
after_success:
  - source $TRAVIS_BUILD_DIR/.integration/TravisScript/update.sh
