# Glob

env:
  - CABALVER=1.22 GHCVERT=7.10.3

before_install:
  - "sudo add-apt-repository -y ppa:hvr/ghc"
  - "sudo apt-get update"
  - "sudo apt-get install ghc-$GHCVER cabal-install-$CABALVER"
  - "export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH"
  - "cabal update"
  - "cabal install directory"
  - "cabal install process"
  - "cabal install yesod -j9"
  - "cabal install persistent-postgresql"
  - "cabal install cmdargs"
script:
  - cabal configure -flaunch-docker
  - cabal build
  - cabal sdist
  - cabal install dist/Glob-*.tar.gz
after_sucess: |
  if [ -n "$GITHUB_API_KEY" ]; then
    git config --global user.name "travis_auto"
    git config --global user.email "qinka@live.com"
    echo '\nconfig done\n'
    cd ~
    git clone https://qinka:$GITHUB_API_KEY@github.com/Release.git
    echo "clone done"
    cd Release/Glob
    ls
    pwd
    export RELPATH=$(pwd)
    ls
    pwd
    cd "$TRAVIS_BUILD_DIR"/src
    ls
    pwd
    cp *.pdf $RELPATH
    echo "copy done"
    cd "$TRAVIS_BUILD_DIR"/dist
    cp *.tar.gz $RELPATH
    cd $RELPATH
    echo " " >> ChangeLog.md
    echo "$(date)" >>ChangeLog.md
    echo " " >> ChangeLog.md
    echo "Travis-CI build Glob's new push."
    git add .
    git commit -am"$(date)"
    echo "commit done"
    git push origin master
    cd ~
    sudo rm -rf $RELPATH
    cd "$TRAVIS_BUILD_DIR"
  fi
