# Glob

env:
  - CABALVER=1.22 GHCVER=7.10.3
services:
  - docker

before_install:
  - "sudo add-apt-repository -y ppa:hvr/ghc"
  - "sudo apt-get update"
  - "sudo apt-get install ghc-$GHCVER cabal-install-$CABALVER"
  - "export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH"
  - "cabal update"
  - "cabal install -j9 directory process persistent-template yesod persistent-postgresql persistent-mongoDB warp-tls cmdargs SHA"
script:
  - cabal configure -flaunch-docker -fwith-postgresql
  - cabal build
  - cabal sdist
  - cabal install dist/Glob-*.tar.gz -fwith-postgresql
  - cabal install dist/Glob-*.tar.gz -fwith-mongodb
  - cabal install dist/Glob-*.tar.gz -flaunch-docker -flaunch-simple -fwith-postgresql
  - cabal install dist/Glob-*.tar.gz -fwith-tls -fwith-postgresql
  - cabal install dist/Glob-*.tar.gz -flaunch-docker -flaunch-simple -fwith-mongodb
  - cabal install dist/Glob-*.tar.gz -fwith-tls -fwith-mongodb
after_script: |
  echo "There should build a docker image."
  rm -rf dist
  cabal configure -flaunch-docker -fwith-postgresql
  cabal build
  ls dist
  ls dist/build/bin
  docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  docker build -f ./dockerfiles/Travis-CI/Dockerfile -t qinka/glob:$TRAVIS_BUILD_NUMBER .
  docker images
  docker push  qinka/glob
