# Glob

env:
  - CABALVER=1.22 GHCVER=7.10.3 GLOB_DB="-fwith-postgresql" GLOB_TLS="-f-with-tls" GLOB_LA="-flaunch-docker" GLOB_DF="./dockerfiles/Travis-CI/PostgreSQL/Dockerfile" GLOB_DT="postgres"
  - CABALVER=1.22 GHCVER=7.10.3 GLOB_DB="-fwith-postgresql" GLOB_TLS="-fwith-tls" GLOB_LA="-flaunch-docker" GLOB_DF="./dockerfiles/Travis-CI/PostgreSQL/Dockerfile" GLOB_DT="postgres-tls"
  - CABALVER=1.22 GHCVER=7.10.3 GLOB_DB="-fwith-mongodb" GLOB_TLS="-f-with-tls" GLOB_LA="-flaunch-docker" GLOB_DF="./dockerfiles/Travis-CI/MongoDB/Dockerfile" GLOB_DT="mongodb"
  - CABALVER=1.22 GHCVER=7.10.3 GLOB_DB="-fwith-mongodb" GLOB_TLS="-fwith-tls" GLOB_LA="-flaunch-docker" GLOB_DF="./dockerfiles/Travis-CI/MongoDB/Dockerfile" GLOB_DT="mongodb-tls"
services:
  - docker

before_install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - "sudo add-apt-repository -y ppa:hvr/ghc"
  - "sudo apt-get update"
  - "sudo apt-get -y install ghc-$GHCVER cabal-install-$CABALVER"
  - "export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH"
  - "cabal update"
  - "cabal install -j9 directory process persistent-template yesod persistent-postgresql persistent-mongoDB warp-tls cmdargs SHA"
script:
  - mkdir dist
  - cd glob-core
  - cabal install $GLOB_DB $GLOB_TLS
  - cd ../glob-main
  - cabal install $GLOB_TLS
  - cd ../glob-launcher
  - cabal configure $GLOB_LA $GLOB_TLS
  - cabal build
  - cp -r dist  ../dist
  - cd ..
after_script: |
  if [ $TRAVIS_TEST_RESULT -eq 0 ]; then
    echo "There should build a docker image."
    rm -rf dist
    if [ -n "$TRAVIS_TAG" ]; then
      export DOCKER_IMAGE_TAG=$GLOB_DT-$TRAVIS_TAG-$TRAVIS_BUILD_NUMBER
    else
      export DOCKER_IMAGE_TAG=$GLOB_DT-$TRAVIS_COMMIT-$TRAVIS_BUILD_NUMBER
    fi
    cp $GLOB_DF dist
    cd dist && docker build -f Dockerfile -t qinka/glob:$DOCKER_IMAGE_TAG . && cd ..
    docker push  qinka/glob
  fi
