# Glob's stack yaml
resolver: lts-8.20

packages:
- glob-auth
- glob-utils
- glob-core
- glob-launch/
# - glob-tools/glob-ih/
# - glob-tools/glob-timecheck/
# - glob-tools/glob-update/

extra-deps: []

flags:
#  glob-core:
#    debug-info: true

extra-package-dbs: []
