# Glob's stack yaml
resolver: lts-9.0

packages:
- glob-auth/
- glob-utils/
- glob-core/
- glob-launch/
- glob-tool/
- submodule/mask/
# - glob-tools/glob-ih/
# - glob-tools/glob-timecheck/
# - glob-tools/glob-update/

extra-deps: []

flags:
#  glob-core:
#    debug-info: true

extra-package-dbs: []
